name: matConomy
version: 0.1
author: Max Ammann
website: https://github.com/maxammann
loadbefore: [ Vault ]

main: org.societies.matconomy.bukkit.BukkitPlugin

commands:
  rconomy:
    description: Main command
    aliases: [money]
    usage: |
       Example: /money - Show your current balance
       Example: /matconomy reload - Reload the plugin


permissions:
  matconomy.*:
    children:
      matconomy.money: true
      matconomy.reload: true
  matconomy.money:
     default: true
  matconomy.reload:
     default: true
